name = Simple
description = A simple 2 column layout demonstrating mobile first and Susy.
preview = preview.png
template = simple-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/simple/simple.layout.css
